### ISSUE TITLE
ValueError Issu

### ISSUE THREAD

**Issue by sam9211** [batzner/indrnn#10]
Hi, 
   Thanks a lot for your work! However when I run the example code I got a Value Error:
_'Variable rnn/multi_rnn_cell/cell_0/ind_rnn_cell/input_kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:...'_
  Could you help to figure out what was went wrong?
  Tanks again!

**Comment by batzner** [comment]
Hi, can you provide details on which code you ran? Was it the `examples/addition_rnn.py` script or the example code in the Readme? Did you run it on `master` or another branch?

I hope, we can find the problem.

**Comment by sam9211** [comment]
I think it's something related with tf.variable_scope. When I run the addition_rnn.py script directly using python everything is OK, but if I copy the code into my Jupyter Notebook and run the bug happened. I have fixed the bug by adding:
_with tf.variable_scope("indrnn", reuse=None):_
in front of 
_output, state = tf.nn.dynamic_rnn(cell, inputs_ph, dtype=tf.float32)_
and make all the rest code within that with loop, then it started running.

**Comment by batzner** [comment]
The error usually occurs, when you run 
`output, state = tf.nn.dynamic_rnn(cell, inputs_ph, dtype=tf.float32)`
twice. Then, it will create the variables again in the second call and complain that they already exist. It might be that you ran the cell Jupyter Notebook twice, so all the variables were already initialized. I have not used TensorFlow in Jupyter yet, but restarting the notebook would probably help in such cases. Apart from that you can also use the `reuse` parameter of a variable scope, as you mentioned above.

**Comment by sam9211** [comment]
Cool!
Tanks again!
