### ISSUE TITLE
Please release the code of action recognition

### ISSUE THREAD

**Issue by CCV-Edward** [batzner/indrnn#16]
In your paper, you have mentioned that the result of action recognition outperform the state-of-the-art work. Could you please release the code of this part?

Thank you a lot!

**Comment by Sunnydreamrain** [comment]
Please refer to [this repo](https://github.com/Sunnydreamrain/IndRNN_Theano_Lasagne). It is also stated in the beginning that [this repo](https://github.com/Sunnydreamrain/IndRNN_Theano_Lasagne) is the original implementation by the authors.

**Comment by CCV-Edward** [comment]
@Sunnydreamrain Thank you
