### ISSUE TITLE
Would you like to contribute this cell to TF's tf.contrib.rnn?

### ISSUE THREAD

**Issue by ebrevdo** [batzner/indrnn#2]
Happy to review your PRs.  May want to address the issue opened by EdeMeijer first.

**Comment by batzner** [comment]
@ebrevdo That would be great! I opened a PR here: [Add IndRNN implementation #17821](https://github.com/tensorflow/tensorflow/pull/17821).

**Comment by batzner** [comment]
TensorFlow's IndRNN implementation can be found [here](https://github.com/tensorflow/tensorflow/blob/f40a875355557483aeae60ffcf757fc9626c752b/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L3057).
