### ISSUE TITLE
how to reimplement the action recognition experiment of the original paper

### ISSUE THREAD

**Issue by jren2019** [batzner/indrnn#20]
hello, could you help share some ideas about how to reimplement the idea on the action recognition dataset? 
I tried to implement this, but the performance is not good, hope you can give some instruction.
my code is here:
https://github.com/jren2019/test_ind
I can give you the data that i used for my code. Thanks

**Comment by batzner** [comment]
Hi @jren2019, I took a look at your code. It seems like you already tried out standard LSTMs and then switched to IndRNN cells, which is a reasonable thing to do. Unfortunately, I currently lack the capacity to dive deep into your code, which would be required to give detailed insights. A general advice would be to look at important papers in the field of action recognition and try to reproduce their results first.

I wish you good luck with your project!

**Comment by Sunnydreamrain** [comment]
@jren2019 Please take a look at the action recognition implementation using IndRNN with Pytorch. That should give you some idea. Thanks.

https://github.com/Sunnydreamrain/IndRNN_pytorch/tree/master/action_recognition
