### ISSUE TITLE
Performance issue in the definition of build_rnn, examples/sequential_mnist.py

### ISSUE THREAD

**Issue by DLPerf** [batzner/indrnn#24]
Hello, I found a performance issue in the definition of `build_rnn`, examples/sequential_mnist.py, [tf.equal in line 201 and 202](https://github.com/batzner/indrnn/blob/67246b513113d8f4cb8b8730a4d521e3f055209a/examples/sequential_mnist.py#L201) will be created repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop in `build_rnn`.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by batzner** [comment]
Thanks for the hint! Commit 8239a81 fixes this.
