### ISSUE TITLE
Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [batzner/indrnn#25]
Hello,I found a performance issue in the definition of `get_training_set` ,
batzner/indrnn/blob/master/examples/sequential_mnist.py,
[dataset.map](https://github.com/batzner/indrnn/blob/67246b513113d8f4cb8b8730a4d521e3f055209a/examples/sequential_mnist.py#L237) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [dataset = dataset.map(preprocess_data)](https://github.com/batzner/indrnn/blob/67246b513113d8f4cb8b8730a4d521e3f055209a/examples/sequential_mnist.py#L245) and
[dataset = dataset.map(preprocess_data)](https://github.com/batzner/indrnn/blob/67246b513113d8f4cb8b8730a4d521e3f055209a/examples/sequential_mnist.py#L252)

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by batzner** [comment]
Thank you for taking a close look at the example! I think for the sake of simplicity, it is okay to leave the data loading as it is.

**Comment by batzner** [comment]
From your recent activity on GitHub it seems like the performance issues that you report in this and other repos are generated (semi-)automatically. If that is the case, it would be helpful to include this info in the descriptions of the respective issues. From a code maintainer's perspective, it makes a difference whether a code analysis program detected a suboptimal order of, say, `shuffle().batch().repeat()` or an actual user encountered an issue with the code.
